remote_theme: jekyll/minima
author:
  name: Rob Van Pamel
  email: "rob.vanpamel@gmail.com"
minima:
  social_links:
    twitter: robvanpamel
    github: rob.vanpamel
    linkedin: rob.vanpamel

plugins:
  - jekyll-remote-theme