title: Rob Van Pamel
description: Rob Van Pamel

author:
  name: Rob Van Pamel
  email: "rob.vanpamel@gmail.com"


show_excerpts: true

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed